# Generated by Django 5.0.6 on 2026-05-25 14:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_taxable', models.BooleanField(default=False)),
                ('monetary_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='companies.company')),
            ],
            options={
                'db_table': 'benefits',
            },
        ),
        migrations.CreateModel(
            name='EmployeeBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('value_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.benefit')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_benefits',
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('days_per_year', models.DecimalField(decimal_places=1, max_digits=5)),
                ('accrual_type', models.CharField(choices=[('monthly', 'Monthly Accrual'), ('annual', 'Annual Grant'), ('manual', 'Manual Grant Only')], default='monthly', max_length=20)),
                ('is_paid', models.BooleanField(default=True)),
                ('carry_forward', models.BooleanField(default=True)),
                ('max_carry_forward', models.IntegerField(default=5)),
                ('requires_approval', models.BooleanField(default=True)),
                ('requires_document', models.BooleanField(default=False)),
                ('min_days', models.IntegerField(default=1)),
                ('max_days_per_request', models.IntegerField(default=14)),
                ('gender_specific', models.CharField(blank=True, choices=[('M', 'Male Only'), ('F', 'Female Only')], help_text='Leave applicable to specific gender only', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='companies.company')),
            ],
            options={
                'db_table': 'leave_types',
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_requested', models.DecimalField(decimal_places=1, max_digits=5)),
                ('reason', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='leave_docs/')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('handover_notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leavetype')),
            ],
            options={
                'db_table': 'leave_applications',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('entitled', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('taken', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('pending', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('carried_forward', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('adjusted', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leavetype')),
            ],
            options={
                'db_table': 'leave_balances',
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
