# Generated by Django 5.0.6 on 2026-05-25 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('trading_name', models.CharField(blank=True, max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('tin', models.CharField(blank=True, max_length=50, verbose_name='Tax Identification Number')),
                ('ssnit_employer_code', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='GH', max_length=2)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('timezone', models.CharField(default='Africa/Accra', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('trial', 'Trial')], default='trial', max_length=20)),
                ('subscription_plan', models.CharField(default='starter', max_length=50)),
                ('max_employees', models.IntegerField(default=50)),
                ('payroll_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('bi_weekly', 'Bi-Weekly'), ('weekly', 'Weekly')], default='monthly', max_length=20)),
                ('payroll_day', models.IntegerField(default=25, help_text='Day of month for payroll processing')),
                ('fiscal_year_start', models.CharField(default='01-01', help_text='MM-DD', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='JobGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'job_grades',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_headquarters', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='companies.company')),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_paye', models.BooleanField(default=True)),
                ('enable_ssnit', models.BooleanField(default=True)),
                ('enable_tier2', models.BooleanField(default=True)),
                ('enable_tier3', models.BooleanField(default=False)),
                ('tier3_employee_rate', models.DecimalField(decimal_places=4, default=0.05, max_digits=5)),
                ('tier3_employer_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('overtime_rate_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('late_penalty_per_minute', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('enable_late_penalty', models.BooleanField(default=False)),
                ('payslip_template', models.CharField(default='standard', max_length=50)),
                ('annual_leave_days', models.IntegerField(default=15)),
                ('sick_leave_days', models.IntegerField(default=14)),
                ('maternity_leave_days', models.IntegerField(default=84)),
                ('paternity_leave_days', models.IntegerField(default=5)),
                ('leave_accrual_method', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('notify_payslip_ready', models.BooleanField(default=True)),
                ('notify_leave_approved', models.BooleanField(default=True)),
                ('notify_loan_approved', models.BooleanField(default=True)),
                ('notify_payroll_processed', models.BooleanField(default=True)),
                ('payment_provider', models.CharField(default='paystack', max_length=30)),
                ('auto_disburse', models.BooleanField(default=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='companies.company')),
            ],
            options={
                'db_table': 'company_settings',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('cost_center', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='companies.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='companies.company')),
            ],
            options={
                'db_table': 'departments',
            },
        ),
    ]
