# Generated by Django 5.0.6 on 2026-05-25 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='companies.department'),
        ),
        migrations.AddField(
            model_name='jobgrade',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_grades', to='companies.company'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='jobgrade',
            unique_together={('company', 'code')},
        ),
    ]
