# Generated by Django 5.0.6 on 2026-05-25 14:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        ('employees', '0001_initial'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_months', models.IntegerField(default=12)),
                ('interest_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('interest_type', models.CharField(choices=[('flat', 'Flat Rate'), ('reducing', 'Reducing Balance'), ('none', 'Interest-Free')], default='none', max_length=20)),
                ('requires_guarantor', models.BooleanField(default=False)),
                ('min_service_months', models.IntegerField(default=6, help_text='Minimum months of service to qualify')),
                ('max_active_loans', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_types', to='companies.company')),
            ],
            options={
                'db_table': 'loan_types',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_number', models.CharField(max_length=30, unique=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_repayment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('repayment_months', models.IntegerField()),
                ('purpose', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('active', 'Active (Repaying)'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('first_repayment_date', models.DateField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='employees.employee')),
                ('guarantor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guaranteed_loans', to='employees.employee')),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loantype')),
            ],
            options={
                'db_table': 'loans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('deducted', 'Deducted from Payroll'), ('paid_directly', 'Paid Directly'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('deducted_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_deductions', to='payroll.payslip')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loan')),
            ],
            options={
                'db_table': 'loan_repayments',
                'ordering': ['due_date'],
                'unique_together': {('loan', 'installment_number')},
            },
        ),
    ]
