# Generated by Django 5.0.6 on 2026-05-25 14:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_year', models.IntegerField()),
                ('band_name', models.CharField(max_length=50)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('cumulative_tax_below', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_monthly', models.BooleanField(default=True)),
                ('country', models.CharField(default='GH', max_length=2)),
            ],
            options={
                'db_table': 'tax_tables',
                'ordering': ['effective_year', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_assignments', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_salaries',
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('pay_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('review', 'Under Review'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_employer_costs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('employee_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('ai_anomalies_detected', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_periods',
                'ordering': ['-period_start'],
                'unique_together': {('company', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='PaymentBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='paystack', max_length=30)),
                ('batch_reference', models.CharField(blank=True, max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('response_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_batches', to='payroll.payrollperiod')),
            ],
            options={
                'db_table': 'payment_batches',
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paye_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ssnit_employee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tier2_employee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tier3_employee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ssnit_employer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tier2_employer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_repayment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_recovery', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('late_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('working_days', models.IntegerField(default=0)),
                ('days_present', models.IntegerField(default=0)),
                ('days_absent', models.IntegerField(default=0)),
                ('leave_days', models.IntegerField(default=0)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('earnings_breakdown', models.JSONField(default=list)),
                ('deductions_breakdown', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('approved', 'Approved'), ('paid', 'Paid'), ('disputed', 'Disputed')], default='draft', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='payslips/')),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('dispute_reason', models.TextField(blank=True)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollperiod')),
            ],
            options={
                'db_table': 'payslips',
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(max_length=20)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payroll.paymentbatch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('payslip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payroll.payslip')),
            ],
            options={
                'db_table': 'payment_records',
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30)),
                ('component_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction'), ('employer_contribution', 'Employer Contribution')], max_length=30)),
                ('calculation_method', models.CharField(choices=[('fixed', 'Fixed Amount'), ('pct_basic', 'Percentage of Basic'), ('pct_gross', 'Percentage of Gross'), ('formula', 'Custom Formula')], default='fixed', max_length=20)),
                ('default_value', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_pensionable', models.BooleanField(default=True, help_text='Include in SSNIT calculation base')),
                ('is_statutory', models.BooleanField(default=False, help_text='Statutory component (SSNIT, PAYE, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('display_on_payslip', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_components', to='companies.company')),
            ],
            options={
                'db_table': 'salary_components',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PayslipComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='payroll.payslip')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.salarycomponent')),
            ],
            options={
                'db_table': 'payslip_components',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('override_method', models.CharField(blank=True, max_length=20)),
                ('employee_salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_overrides', to='payroll.employeesalary')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.salarycomponent')),
            ],
            options={
                'db_table': 'employee_salary_components',
            },
        ),
        migrations.CreateModel(
            name='CustomPayrollRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('always', 'Always Apply'), ('dept', 'If Department'), ('grade', 'If Job Grade'), ('emp_type', 'If Employment Type'), ('tax', 'If Tax Treatment'), ('tenure', 'If Years of Service'), ('salary', 'If Salary Range'), ('formula', 'Custom Formula')], max_length=20)),
                ('trigger_condition', models.JSONField(default=dict, help_text='Trigger parameters (dept_id, grade_id, etc.)')),
                ('action_type', models.CharField(choices=[('add', 'Add Amount'), ('set', 'Set Amount'), ('multiply', 'Multiply By'), ('formula', 'Apply Formula')], max_length=20)),
                ('action_value', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('action_formula', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher = applied later (can override)')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_rules', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.salarycomponent')),
            ],
            options={
                'db_table': 'custom_payroll_rules',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='companies.company')),
            ],
            options={
                'db_table': 'salary_structures',
            },
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.salarystructure'),
        ),
        migrations.CreateModel(
            name='SalaryStructureComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('calculation_method', models.CharField(blank=True, max_length=20)),
                ('formula', models.TextField(blank=True, help_text='Python-safe formula expression')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.salarycomponent')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_components', to='payroll.salarystructure')),
            ],
            options={
                'db_table': 'salary_structure_components',
            },
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='components',
            field=models.ManyToManyField(through='payroll.SalaryStructureComponent', to='payroll.salarycomponent'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['employee', 'status'], name='payslips_employe_6a3786_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('payroll_period', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='salarycomponent',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='employeesalarycomponent',
            unique_together={('employee_salary', 'component')},
        ),
        migrations.AddIndex(
            model_name='employeesalary',
            index=models.Index(fields=['employee', 'is_current'], name='employee_sa_employe_650370_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salarystructurecomponent',
            unique_together={('structure', 'component')},
        ),
        migrations.AlterUniqueTogether(
            name='salarystructure',
            unique_together={('company', 'code')},
        ),
    ]
