# Generated by Django 5.0.6 on 2026-09-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_paystack_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile_money_provider',
            field=models.CharField(blank=True, choices=[('mtn', 'MTN Mobile Money'), ('vodafone', 'Telecel Cash'), ('airteltigo', 'AirtelTigo Money')], max_length=20),
        ),
    ]
